### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by shinoomata** [shinoomata/Aqua_voyage#97]
## 各種情報
AQUA VOYAGE 〜水族館めぐり〜
https://aqua-voyage.fly.dev/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] Google認証
- [x] 水族館検索・一覧
   - 施設名
   - 地域
- [x] 水族館詳細
  - [x] Googlemap表示
  - [x] Googlemapから施設の写真取得 
- [x] 推しポイント投稿
　　　- レーティング（大人向けかファミリー向けか等）

## 本リリース時
- [ ] タグ付け機能（生き物・推しポイント）
- [ ] お気に入り機能
- [ ] おすすめの水族館表示（レコメンド）
- [ ] 写真投稿（画像加工）
- [ ] 位置情報から検索
- [ ] 称号機能（口コミを行った数に応じて称号をゲット）→ランキング機能に変更予定

## 必要なページ

- [x] トップページ
- [x] Google認証ページ
- [x] 水族館検索＆一覧
- [x] 水族館詳細ページ
- [x] レビュー投稿ページ
- [ ] マイページ（レビュー一覧、お気に入り確認）
- [ ] 新着レビューページ
- [ ] お問い合わせ
- [ ] プライバシーポリシー
- [ ] 利用規約

## READMEレビュー時から変更した機能
会員登録をGoogle認証のみとしました。
READMEレビュー時より、面談などを通して機能を絞りました。
施設の写真については、実装できたので追加しました。

## サービスイメージがわかるようなスクリーンショット等
| トップページ | 水族館検索画面 |
| ---- | ---- |
| [![Image from Gyazo](https://i.gyazo.com/46a9ede817faf773b010a9d6d8b1ef4a.gif)](https://gyazo.com/46a9ede817faf773b010a9d6d8b1ef4a) | [![Image from Gyazo](https://i.gyazo.com/b3f2c1de02072a8cfd634a2507bfaea2.gif)](https://gyazo.com/b3f2c1de02072a8cfd634a2507bfaea2) |
| ---- | ---- |
| 水族館詳細 | レビュー投稿画面 |
| :----: | :----: |
| [![Image from Gyazo](https://i.gyazo.com/7f34a2f4516f64b61a4ae9b8aa3d70ee.gif)](https://gyazo.com/7f34a2f4516f64b61a4ae9b8aa3d70ee) | [![Image from Gyazo](https://i.gyazo.com/a34b7c01aedad26a7fb2e674fdfbb32b.gif)](https://gyazo.com/a34b7c01aedad26a7fb2e674fdfbb32b) |

**Comment by shinoomata** [comment]
[![Image from Gyazo](https://i.gyazo.com/6a66feeb20a6e46055e033d4e8d88934.gif)](https://gyazo.com/6a66feeb20a6e46055e033d4e8d88934)

**Comment by kenchasonakai** [comment]
LGTMです！
